### PR TITLE
Serial port name compatibility fix for Mac

### PR DESCRIPTION
**Pull request by wabisabit**
The text field was too narrow for the names serial ports have on macs,
so I moved it under the buttons.

### CODE REVIEW

**Comment by rogeriobego** [comment]
Roman, thanks for your help!
I do not have a Mac and I apreciate a help with that.
Can you show me some serial port names for Mac?
I will use your idea to change the code. I will make little adjusts using it.

**Comment by wabisabit** [comment]
Sure, here are my current ports:
screen shot 2017-06-16 at 11 27 52
screen shot 2017-06-16 at 11 29 17
I'm glad I can help. Your project is very useful for me! Thank you!

**Comment by rogeriobego** [comment]
Roman,
Please, try the last version (v1.2.2)

**Comment by wabisabit** [comment]
That works too, thank you!

**Pull request closed without merging**
